production: false

operator_address: 0x8e5171651c7c72020278019b45f7dbb067e76b91

el_slasher_address: 0x5FC8d32690cc91D4c39d9d3abcBD16989F875707
avs_service_manager_address: 0xc3e53F4d16Ae77Db1c982e75a937B9f60FE63690
bls_operator_state_retriever_address: 0xa85233C63b9Ee964Add6F2cffe00Fd84eb32338f
bls_public_key_compendium_address: 0x322813Fd9A801c5507c9de605d63CEA4f2CE6c44

eth_rpc_url: http://anvil:8545
eth_ws_url: ws://anvil:8545

ecdsa_private_key_store_path: docker-compose/operators/keys/ecdsa-b9e518b6-b074-11ee-b1e3-a036bcd1ceee/keys/8.ecdsa.key.json
bls_private_key_store_path: docker-compose/operators/keys/bls-bcdefdc3-b074-11ee-b1e3-a036bcd1ceee/keys/8.bls.key.json

aggregator_server_ip_port_address: incredible-squaring-aggregator:8090

enable_metrics: true
eigen_metrics_ip_port_address: 0.0.0.0:9090

enable_node_api: true
node_api_ip_port_address: 0.0.0.0:9010

register_operator_on_startup: true
